from pathlib import Path


class _Axes:
    pass


class _Figure:
    def add_subplot(self, *_args, **_kwargs):
        return _Axes()

    def savefig(self, filename):
        Path(filename).write_text("placeholder image generated by fallback matplotlib")


def figure():
    return _Figure()
